apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hairpin-proxy.fullname" . }}
  labels:
    app.kubernetes.io/component: haproxy
    {{- include "hairpin-proxy.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
