{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "hairpin-proxy.fullname" . }}-psp
  labels:
{{- include "hairpin-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "hairpin-proxy.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ include "hairpin-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

