{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hairpin-proxy.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "hairpin-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hairpin-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hairpin-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
